#!/usr/bin/env bash

reproera_print_plan_recursive() {
    local package="$1"
    local version="$2"
    local dependency dep_version
    for dependency in $(reproera_recipe_dependencies "$package"); do
        dep_version="$(reproera_default_version "$dependency")"
        reproera_print_plan_recursive "$dependency" "$dep_version"
    done
    printf '%s@%s\n' "$package" "$version"
}

reproera_plan() {
    if [[ "$#" -eq 0 ]]; then
        local project_spec project_specs_text
        project_specs_text="$(reproera_project_specs)" || return 1
        while IFS= read -r project_spec; do
            reproera_plan "$project_spec"
        done <<<"$project_specs_text" | awk '!seen[$0]++'
        return
    fi
    [[ "$#" -eq 1 ]] || reproera_die "usage: reproera plan [PACKAGE[@VERSION]]"
    local resolved package version
    resolved="$(reproera_resolve_spec "$1")" || reproera_die "unsupported package or version: $1"
    package="${resolved%% *}"
    version="${resolved#* }"
    reproera_print_plan_recursive "$package" "$version" | awk '!seen[$0]++'
}

reproera_init_project() {
    local config="$PWD/reproera.toml" resolved package version spec
    local specifications=()

    [[ ! -e "$config" ]] || reproera_die "project already initialized: $config"
    if [[ "$#" -eq 0 ]]; then
        set -- python
    fi
    for spec in "$@"; do
        resolved="$(reproera_resolve_spec "$spec")" \
            || reproera_die "unsupported package or version: $spec"
        package="${resolved%% *}"
        version="${resolved#* }"
        specifications+=("$package = \"$version\"")
    done

    mkdir -p "$PWD/.reproera"
    {
        printf '# Reproera project environment\n'
        printf '# Generated by reproera init; edit pinned versions explicitly.\n\n'
        printf '[environment]\n'
        printf '%s\n' "${specifications[@]}"
    } >"$config"
    printf '*\n!.gitignore\n' >"$PWD/.reproera/.gitignore"
    reproera_info "initialized project at $PWD"
    reproera_info "configuration: $config"
}

reproera_build_one() {
    local package="$1"
    local version="$2"
    local prefix="$3"
    local jobs="$4"
    local cache_dir state_dir archive url sha source_parent source_dir marker prefix_id
    cache_dir="$(reproera_cache_dir)/sources"
    state_dir="$(reproera_state_dir)"
    archive="${cache_dir}/$(reproera_recipe_archive "$package" "$version")"
    url="$(reproera_recipe_url "$package" "$version")"
    sha="$(reproera_recipe_sha256 "$package" "$version")"
    source_parent="$(reproera_safe_build_dir "$state_dir" "$package" "$version")"
    prefix_id="$(reproera_string_sha256 "$prefix")"
    marker="${state_dir}/installed/${prefix_id}/${package}-${version}"

    if [[ -f "$marker" ]]; then
        reproera_info "$package@$version is already installed"
        return
    fi

    reproera_info "downloading $package@$version"
    reproera_download "$url" "$archive" || reproera_die "download failed: $url"
    reproera_verify_archive "$archive" "$sha"
    reproera_extract_archive "$archive" "$source_parent"
    source_dir="$(find "$source_parent" -mindepth 1 -maxdepth 1 -type d | head -n 1)"
    [[ -n "$source_dir" ]] || reproera_die "could not locate extracted source directory"

    reproera_info "building $package@$version with ${CC:-cc}"
    if ! reproera_run_recipe "$package" "$source_dir" "$prefix" "$jobs"; then
        reproera_warn "retaining failed build tree: $source_parent"
        return 1
    fi
    reproera_verify_install "$package" "$prefix"
    mkdir -p "$(dirname "$marker")"
    printf 'prefix=%s\ninstalled_at=%s\n' "$prefix" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$marker"
}

reproera_install_marker() {
    local package="$1" version="$2" prefix="$3" prefix_id
    prefix_id="$(reproera_string_sha256 "$prefix")"
    printf '%s/installed/%s/%s-%s\n' \
        "$(reproera_state_dir)" "$prefix_id" "$package" "$version"
}

reproera_run_recipe() {
    local package="$1" source_dir="$2" prefix="$3" jobs="$4"
    case "$package" in
        zlib)
            (cd "$source_dir" && ./configure --prefix="$prefix" && make -j"$jobs" && make install)
            ;;
        bzip2)
            (cd "$source_dir" && make -j"$jobs" \
                CFLAGS="-fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64" && \
                make install PREFIX="$prefix")
            ;;
        xz)
            (cd "$source_dir" && ./configure --prefix="$prefix" --libdir="$prefix/lib" && \
                make -j"$jobs" && make install)
            ;;
        libffi)
            (cd "$source_dir" && ./configure --prefix="$prefix" \
                --libdir="$prefix/lib" --includedir="$prefix/include" \
                --disable-multi-os-directory && \
                make -j"$jobs" && make install)
            ;;
        sqlite)
            (cd "$source_dir" && ./configure --prefix="$prefix" \
                --disable-static --disable-readline && \
                make -j"$jobs" && make install)
            ;;
        perl)
            (cd "$source_dir" && sh Configure -des \
                -Dprefix="$prefix" -Dman1dir=none -Dman3dir=none && \
                make -j"$jobs" && make install)
            ;;
        openssl)
            (cd "$source_dir" && CPPFLAGS="-I$prefix/include ${CPPFLAGS:-}" \
                LDFLAGS="-L$prefix/lib -Wl,-rpath,$prefix/lib ${LDFLAGS:-}" \
                "$prefix/bin/perl" ./Configure \
                --prefix="$prefix" --openssldir="$prefix/ssl" \
                --libdir=lib \
                shared zlib --with-zlib-include="$prefix/include" \
                --with-zlib-lib="$prefix/lib" && \
                make -j"$jobs" build_libs && \
                make -j"$jobs" build_modules && \
                make -j"$jobs" build_programs && \
                make install_sw)
            ;;
        ncurses)
            (cd "$source_dir" && ./configure --prefix="$prefix" --with-shared \
                --without-debug --without-ada --enable-widec --enable-pc-files \
                --with-pkg-config-libdir="$prefix/lib/pkgconfig" && \
                make -j"$jobs" && make install)
            ;;
        readline)
            (cd "$source_dir" && CPPFLAGS="-I$prefix/include -I$prefix/include/ncursesw ${CPPFLAGS:-}" \
                LDFLAGS="-L$prefix/lib -Wl,-rpath,$prefix/lib ${LDFLAGS:-}" \
                ./configure --prefix="$prefix" --libdir="$prefix/lib" --with-curses && \
                make -j"$jobs" SHLIB_LIBS="-L$prefix/lib -Wl,-rpath,$prefix/lib -lncursesw" && \
                make install)
            ;;
        libevent)
            (cd "$source_dir" && PKG_CONFIG_PATH="$prefix/lib/pkgconfig:${PKG_CONFIG_PATH:-}" \
                CPPFLAGS="-I$prefix/include ${CPPFLAGS:-}" \
                LDFLAGS="-L$prefix/lib -Wl,-rpath,$prefix/lib ${LDFLAGS:-}" \
                ./configure --prefix="$prefix" --disable-openssl && \
                make -j"$jobs" && make install)
            ;;
        python)
            (cd "$source_dir" && CPPFLAGS="-I$prefix/include -I$prefix/include/ncursesw ${CPPFLAGS:-}" \
                LDFLAGS="-L$prefix/lib -Wl,-rpath,$prefix/lib ${LDFLAGS:-}" \
                PKG_CONFIG_PATH="$prefix/lib/pkgconfig:${PKG_CONFIG_PATH:-}" \
                ./configure --prefix="$prefix" --with-openssl="$prefix" \
                --with-openssl-rpath=auto --with-ensurepip=install && \
                make -j"$jobs" && make altinstall)
            ;;
        tmux)
            (cd "$source_dir" && CPPFLAGS="-I$prefix/include -I$prefix/include/ncursesw ${CPPFLAGS:-}" \
                LDFLAGS="-L$prefix/lib -Wl,-rpath,$prefix/lib ${LDFLAGS:-}" \
                PKG_CONFIG_PATH="$prefix/lib/pkgconfig:${PKG_CONFIG_PATH:-}" \
                ./configure --prefix="$prefix" && make -j"$jobs" && make install)
            ;;
        *) reproera_die "no build recipe for $package" ;;
    esac
}

reproera_verify_install() {
    local package="$1" prefix="$2"
    case "$package" in
        zlib)
            [[ -f "$prefix/include/zlib.h" ]] || reproera_die "zlib verification failed"
            ;;
        bzip2)
            [[ -f "$prefix/include/bzlib.h" && -f "$prefix/lib/libbz2.a" ]] \
                || reproera_die "bzip2 verification failed"
            ;;
        xz)
            [[ -f "$prefix/include/lzma.h" && -f "$prefix/lib/liblzma.so" ]] \
                || reproera_die "xz verification failed"
            ;;
        libffi)
            [[ -f "$prefix/include/ffi.h" && -f "$prefix/lib/libffi.so" ]] \
                || reproera_die "libffi verification failed"
            ;;
        sqlite)
            "$prefix/bin/sqlite3" -version >/dev/null || reproera_die "SQLite verification failed"
            ;;
        perl)
            "$prefix/bin/perl" -MIPC::Cmd -MTime::Piece -e 1 \
                || reproera_die "Perl verification failed"
            ;;
        openssl)
            "$prefix/bin/openssl" version >/dev/null || reproera_die "OpenSSL verification failed"
            ;;
        ncurses)
            [[ -f "$prefix/include/ncursesw/ncurses.h" ]] || reproera_die "ncurses verification failed"
            ;;
        readline)
            [[ -f "$prefix/include/readline/readline.h" && -f "$prefix/lib/libreadline.so" ]] \
                || reproera_die "readline verification failed"
            ;;
        libevent)
            [[ -f "$prefix/include/event2/event.h" ]] || reproera_die "libevent verification failed"
            ;;
        python)
            "$prefix/bin/python3.11" -c 'import bz2, ctypes, curses, lzma, readline, sqlite3, ssl, zlib' \
                || reproera_die "Python verification failed: a required native module is unavailable"
            ;;
        tmux)
            "$prefix/bin/tmux" -V >/dev/null || reproera_die "tmux verification failed"
            ;;
    esac
}

reproera_print_activation_guidance() {
    local prefix="$1" project_root shell_name
    shell_name="${SHELL:-bash}"
    shell_name="${shell_name##*/}"
    if project_root="$(reproera_find_project_root)" && \
        [[ "$prefix" == "$project_root/.reproera/prefix" ]]; then
        case "$shell_name" in
            tcsh|csh)
                printf '  Activate:     source %s/.reproera/activate.tcsh\n' "$project_root"
                ;;
            *)
                printf '  Activate:     source %s/.reproera/activate\n' "$project_root"
                ;;
        esac
    else
        case "$shell_name" in
            tcsh|csh)
                printf '  Activate:     reproera shell-init tcsh --apply, then start a new shell\n'
                ;;
            *)
                printf '  Activate:     eval "$(reproera env %s)"\n' \
                    "${shell_name:-bash}"
                ;;
        esac
    fi
}

reproera_environment_active() {
    local prefix="$1"
    case ":${PATH}:" in
        *:"$prefix/bin":*) return 0 ;;
        *) return 1 ;;
    esac
}

reproera_print_install_summary() {
    local prefix="$1" plan_text="$2" package_count
    package_count="$(printf '%s\n' "$plan_text" | awk 'NF { count++ } END { print count + 0 }')"
    printf '\nReproera installation complete\n'
    printf '  Prefix:       %s\n' "$prefix"
    printf '  Verification: passed (%s/%s packages)\n' "$package_count" "$package_count"
    if reproera_environment_active "$prefix"; then
        printf '  Environment:  active in this shell\n'
    else
        printf '  Environment:  NOT ACTIVE in this shell\n'
        reproera_print_activation_guidance "$prefix"
    fi
    printf '  Confirm with: reproera verify\n'
}

reproera_verify() {
    [[ "$#" -le 1 ]] || reproera_die "usage: reproera verify [PACKAGE[@VERSION]]"

    local prefix canonical_prefix plan_text plan_line package version marker
    local checked=0 failed=0
    prefix="$(reproera_default_prefix)"
    if [[ ! -d "$prefix" ]]; then
        reproera_die "installation prefix does not exist: $prefix"
    fi
    canonical_prefix="$(cd "$prefix" && pwd -P)"
    if [[ "$#" -eq 1 ]]; then
        plan_text="$(reproera_plan "$1")"
    else
        plan_text="$(reproera_plan)"
    fi

    printf 'Reproera verification\n'
    printf '  Prefix: %s\n' "$canonical_prefix"
    while IFS= read -r plan_line; do
        [[ -n "$plan_line" ]] || continue
        package="${plan_line%%@*}"
        version="${plan_line#*@}"
        marker="$(reproera_install_marker "$package" "$version" "$canonical_prefix")"
        checked=$((checked + 1))
        if [[ ! -f "$marker" ]]; then
            printf '  [missing] %s\n' "$plan_line"
            failed=$((failed + 1))
        elif (reproera_verify_install "$package" "$canonical_prefix") >/dev/null 2>&1; then
            printf '  [ok]      %s\n' "$plan_line"
        else
            printf '  [failed]  %s\n' "$plan_line"
            failed=$((failed + 1))
        fi
    done <<<"$plan_text"

    if reproera_environment_active "$canonical_prefix"; then
        printf '  [ok]      shell uses %s/bin\n' "$canonical_prefix"
    else
        printf '  [inactive] current shell does not use %s/bin\n' "$canonical_prefix"
        reproera_print_activation_guidance "$canonical_prefix"
        failed=$((failed + 1))
    fi

    if [[ "$failed" -eq 0 ]]; then
        printf 'Verified: %s/%s packages; environment active.\n' "$checked" "$checked"
        return 0
    fi
    printf 'Verification needs attention: %s issue(s).\n' "$failed" >&2
    return 1
}

reproera_check_plan_requirements() {
    local spec="$1" plan_line package command missing=0
    while IFS= read -r plan_line; do
        package="${plan_line%%@*}"
        for command in $(reproera_recipe_required_commands "$package"); do
            if ! reproera_command_exists "$command"; then
                reproera_warn "$package requires missing command: $command"
                missing=1
            fi
        done
    done < <(reproera_plan "$spec")
    [[ "$missing" -eq 0 ]]
}

reproera_install() {
    if [[ "$#" -eq 0 || "${1:-}" == -* ]]; then
        local project_spec project_specs_text project_plan canonical_project_prefix
        local project_options=("$@")
        project_specs_text="$(reproera_project_specs)" || return 1
        project_plan="$(reproera_plan)" || return 1
        while IFS= read -r project_spec; do
            REPROERA_INSTALL_SUMMARY=0 \
                reproera_install "$project_spec" "${project_options[@]}"
        done <<<"$project_specs_text"
        if [[ "${REPROERA_INSTALL_SUMMARY:-1}" -eq 1 && \
            " ${project_options[*]} " != *' --dry-run '* ]]; then
            canonical_project_prefix="$(reproera_realpath_dir "$(reproera_default_prefix)")"
            reproera_print_install_summary "$canonical_project_prefix" "$project_plan"
        fi
        return
    fi

    local spec="$1" prefix jobs dry_run=0
    shift
    prefix="$(reproera_default_prefix)"
    jobs="$(reproera_cpu_count)"

    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            --prefix)
                [[ "$#" -ge 2 ]] || reproera_die "--prefix requires a path"
                prefix="$2"; shift 2 ;;
            --jobs|-j)
                [[ "$#" -ge 2 && "$2" =~ ^[1-9][0-9]*$ ]] || reproera_die "--jobs requires a positive integer"
                jobs="$2"; shift 2 ;;
            --dry-run) dry_run=1; shift ;;
            *) reproera_die "unknown install option: $1" ;;
        esac
    done

    local plan_line package version canonical_prefix
    if [[ "$dry_run" -eq 1 ]]; then
        reproera_info "dry run; prefix=$prefix jobs=$jobs"
        reproera_plan "$spec"
        return
    fi

    reproera_check_writable_prefix "$prefix" || reproera_die "prefix is not writable: $prefix"
    canonical_prefix="$(reproera_realpath_dir "$prefix")"
    REPROERA_PREFIX="$canonical_prefix" reproera_doctor_text >/dev/null \
        || reproera_die "doctor found blocking problems"
    reproera_check_plan_requirements "$spec" || reproera_die "package build requirements are missing"
    while IFS= read -r plan_line; do
        package="${plan_line%%@*}"
        version="${plan_line#*@}"
        reproera_build_one "$package" "$version" "$canonical_prefix" "$jobs" \
            || reproera_die "build failed: $package@$version"
    done < <(reproera_plan "$spec")

    if [[ "${REPROERA_INSTALL_SUMMARY:-1}" -eq 1 ]]; then
        reproera_print_install_summary "$canonical_prefix" "$(reproera_plan "$spec")"
    fi
}

reproera_emit_environment() {
    local shell_name="$1" prefix="$2"
    case "$shell_name" in
        bash|zsh)
            printf 'export PATH="%s/bin:$PATH"\n' "$prefix"
            printf 'export PKG_CONFIG_PATH="%s/lib/pkgconfig:%s/lib64/pkgconfig:${PKG_CONFIG_PATH:-}"\n' "$prefix" "$prefix"
            printf 'export LD_LIBRARY_PATH="%s/lib:%s/lib64:${LD_LIBRARY_PATH:-}"\n' "$prefix" "$prefix"
            ;;
        tcsh|csh)
            printf 'setenv PATH "%s/bin:${PATH}"\n' "$prefix"
            printf 'rehash\n'
            printf 'if ( $?PKG_CONFIG_PATH ) then\n'
            printf '  setenv PKG_CONFIG_PATH "%s/lib/pkgconfig:%s/lib64/pkgconfig:${PKG_CONFIG_PATH}"\n' "$prefix" "$prefix"
            printf 'else\n  setenv PKG_CONFIG_PATH "%s/lib/pkgconfig:%s/lib64/pkgconfig"\nendif\n' "$prefix" "$prefix"
            printf 'if ( $?LD_LIBRARY_PATH ) then\n'
            printf '  setenv LD_LIBRARY_PATH "%s/lib:%s/lib64:${LD_LIBRARY_PATH}"\n' "$prefix" "$prefix"
            printf 'else\n  setenv LD_LIBRARY_PATH "%s/lib:%s/lib64"\nendif\n' "$prefix" "$prefix"
            ;;
        *) reproera_die "unsupported shell: $shell_name" ;;
    esac
}

reproera_emit_shell_init() {
    local shell_name="$1"
    case "$shell_name" in
        bash) printf '\n# Reproera\neval "$(reproera env bash)"\n' ;;
        zsh) printf '\n# Reproera\neval "$(reproera env zsh)"\n' ;;
        tcsh|csh)
            printf '\n# Reproera\n'
            reproera_emit_environment tcsh "$(reproera_default_prefix)"
            ;;
        *) reproera_die "unsupported shell: $shell_name" ;;
    esac
}

reproera_apply_shell_init() {
    local shell_name="$1" rc_file marker
    case "$shell_name" in
        bash) rc_file="${HOME}/.bashrc" ;;
        zsh) rc_file="${HOME}/.zshrc" ;;
        tcsh|csh) rc_file="${HOME}/.cshrc" ;;
        *) reproera_die "unsupported shell: $shell_name" ;;
    esac
    marker="# Reproera"
    if [[ -f "$rc_file" ]] && grep -Fq "$marker" "$rc_file"; then
        reproera_info "$rc_file already contains Reproera initialization"
        return
    fi
    if [[ -f "$rc_file" ]]; then
        cp -p "$rc_file" "${rc_file}.reproera.bak"
        reproera_info "backup written to ${rc_file}.reproera.bak"
    fi
    reproera_emit_shell_init "$shell_name" >>"$rc_file"
    reproera_info "updated $rc_file"
}
